version: "3.9"

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:p6spy:mysql://db:3306/todo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - spring_1

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'todo'
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/resources/todo_task.sql:/docker-entrypoint-initdb.d/init.sql
      - my-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10
    networks:
      - spring_1

volumes:
  my-db:

networks:
  spring_1:
    driver: bridge